### ISSUE TITLE
TeXLive:  File `TangramTikz.sty' not found

### ISSUE THREAD

**Issue by GMS103** [cpierquet/TangramTikz#1]
TeX Live Utility does not succeed in installing this.
The file TangramTikz.sty is nowhere to be found.
The only new file is
/usr/local/texlive/2022/tlpkg/tlpobj/tangramtikz.tlpobj

**Comment by cpierquet** [comment]
The archive is correct inside CTAN server, not in TeXlive but I don't know why...
I sent a message but no answer for the moment...

**Comment by cpierquet** [comment]
It's OK now ;-)
![image](https://user-images.githubusercontent.com/45103962/215254599-247ac3c7-4c5c-4435-ad47-2d54d08a8262.png)

**Comment by GMS103** [comment]
Yes, it works now, merci beaucoup !
